# GitHub Pages (https://pages.github.com/versions/)
# Ruby version
language: ruby
rvm:
  - 2.5.8

before_script:
  - chmod +x ./script/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler

git:
  depth: 10

notifications:
  email: false
