language: ruby
rvm: 2.5.3
cache: bundler
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script: chmod +x ./scripts/cibuild
script: ./scripts/cibuild

branches:
  only:
    - master

git:
  depth: 10

notifications:
  email: false
