# Jekyll configuration (https://jekyllrb.com/docs/configuration/)

title: "Milan Aryal"
tagline: "Livin' on the edge"
description: "I'm just a regular person who believes life is simple, and I like a simple life."
url: "https://milanaryal.com.np"
logo: "/assets/img/open-graph.png"
theme_color: "#111111"
words_per_minute: 180

nav:
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

author:
  name: "Milan Aryal"
  uri: "https://twitter.com/MilanAryal"
  avatar: "/assets/img/avatar.png"
  bio: "I'm just a regular person who believes life is simple, and I like a simple life."
  gender: "Male"
  nationality: "Nepal"
  facebook: "considermilan"
  twitter: "MilanAryal"
  telegram: "MilanAryal"
  instagram: "MilanAryal"
  github: "MilanAryal"
  keybase: "milanaryal"

# SEO
twitter:
  username: "MilanAryal"
  card: summary
# SEO JSON-LD
social:
  name: "Milan Aryal"
  links:
    - https://twitter.com/MilanAryal
    - https://github.com/MilanAryal
    - https://keybase.io/milanaryal
    - https://www.linkedin.com/in/milanaryal
    - https://www.pinterest.com/milanaryal
    - https://www.instagram.com/milanaryal
    - https://www.facebook.com/considermilan

disqus_shortname: "milanaryal"
google_cse_id: "000254926668963224856:z4vgwqv7kla"
google_api_key: "AIzaSyB27uh5sPHJ156nRryf1yuJn6fjo_B7qvI"
google_analytics_id: "UA-42092423-1"
google_analytics_id_2: "UA-42092423-2"

# HTML language attribute format eg. en, en-US, en-GB ...
# lang: "en"

# Open Graph protocol format eg. en_US, en_GB ...
# locale: "en_US"

# Jekyll default configuration
# Read: https://jekyllrb.com/docs/configuration/default/

repository: "MilanAryal/milanaryal.github.io"
branch: "master"
encoding: "utf-8"
future: true
timezone: "Asia/Kathmandu"

kramdown:
  toc_levels: [2, 3]

gist:
  noscript: false

paginate_path: "/blog/:num/"
paginate: 10
permalink: "/:title/"

defaults:
  - scope:
      path: ""
    values:
      twitter:
        card: summary
      thumbnail:
        path: "/assets/img/open-graph.png"
        width: 300
        height: 300
  - scope:
      path: ""
      type: "pages"
    values:
      twitter:
        card: summary
      image:
        path: "/assets/img/open-graph.png"
        width: 300
        height: 300
      feature_image:
        path: "/assets/img/default.jpg"
        width: 1500
        height: 500
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: "uploads/**/*.pdf"
    values:
      sitemap: false

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# HTML compression (https://jch.penibelst.de/)
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development
  profile: false

include:
  - "_pages"

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - bundle
  - ".bundle"
  - script
  - vendor
  - src
  - node_modules
  - package.json
  - package-lock.json
  - npm-debug.log
  - webpack.config.js
  - postcss.config.js
