#!/usr/bin/env bash

chmod +x script/branding
script/branding

set -e

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

title "List dependency versions"
bundle exec github-pages versions

title "Checking DNS"
bundle exec github-pages health-check

title "Building site"
bundle exec jekyll build --config _config.yml,_config_test.yml --profile

title "Checking Jekyll configuration"
bundle exec jekyll doctor

title "Checking HTML files"
bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --check-external-hash --check-favicon --check-img-http --check-opengraph --disable-external --empty-alt-ignore --internal-domains "milanaryal.com.np" --http-status-ignore "403,429" --only-4xx

title "Cleaning up..."
bundle exec jekyll clean
