#!/bin/bash

set -ev

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

script/branding

title "List dependency versions"
bundle exec github-pages versions

title "Checking DNS"
bundle exec github-pages health-check

title "Building site"
bundle exec jekyll build --config _config.yml,_config_test.yml

title "Checking HTML files"
bundle exec htmlproofer ./_site --only-4xx

title "Cleaning up..."
rm -rf _site
