name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**"
      - "!.github/workflows/**"
      - "!_config.yml"
      - "!src/**"

env:
  RUBY_VERSION: 2.7

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }} # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Version info
        run: |
          ruby --version
          gem --version
          bundle --version

      - name: Checking Jekyll configuration
        run: bundle exec jekyll doctor

      - name: Checking Markdown files
        run: bundle exec mdl --ignore-front-matter --style .mdl_style.rb src/_posts || true

      - name: Building site
        run: JEKYLL_ENV=production bundle exec jekyll build --profile --trace --verbose

      # - name: Install Minify deb package on Ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: apt-get update && apt-get install --no-install-recommends --yes minify

      # https://github.com/tdewolff/homebrew-tap/
      - name: Install Minify using Homebrew
        run: brew install tdewolff/tap/minify

      # https://github.com/tdewolff/minify/tree/master/cmd/minify#usage
      - name: Minify HTML files
        run: |
          minify --type=html --recursive --output . --match=\.html ./_site/ \
          --html-keep-default-attrvals \
          --html-keep-document-tags \
          --html-keep-end-tags \
          --verbose

      - name: Minify JSON files
        run: |
          minify --type=json --recursive --output . --match=\.json ./_site/ --verbose || true \
          && \
          minify --type=json --output . ./_site/manifest.webmanifest --verbose || true

      - name: Checking HTML files
        run: |
          bundle exec htmlproofer ./_site \
          --allow-hash-href \
          --assume-extension \
          --check-external-hash \
          --check-favicon \
          --check-img-http \
          --check-opengraph \
          --internal-domains "milanaryal.com.np" \
          --http-status-ignore "403,429" \
          --only-4xx \
          --file_ignore "/.+\/example-content.+/,/.+\/googleca1cec34378dc996.html/,/.+\/pinterest-eac13.html/,/.+\/random\/index.html/,/.+\/style-guide\/index.html/" \
          || true

      - name: Upload site
        uses: actions/upload-artifact@v3
        if: success() && github.repository == 'MilanAryal/milanaryal.github.io' && github.ref == 'refs/heads/main'
        with:
          name: site
          path: ./_site/
          if-no-files-found: error

      - name: Cleaning up
        run: bundle exec jekyll clean

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'MilanAryal/milanaryal.github.io' && github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: ./_site/

      - name: List files and folders
        run: ls .

      - name: List site files and folders
        run: ls ./_site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site/
